In [1]:
import matplotlib.pyplot as plt
import numpy
import pandas

# Numpy 操作


In [4]:
#导入库
import numpy as np 

In [7]:
#创建数组
data=np.arange(12).reshape(3,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
#数据类型
type(data)

numpy.ndarray

In [10]:
#数组维度个数
data.ndim

2

In [12]:
#数组维度
data.shape

(3, 4)

In [13]:
#数组元素个数
data.size

12

In [14]:
#数组元素类型
data.dtype

dtype('int32')

In [16]:
#创建一维数组
data1=np.array([1,2,3])
data1

array([1, 2, 3])

In [18]:
#创建二维数组
data2=np.array([[1,2,3],[4,5,6]])
data2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
#全0数组
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [20]:
#全空数组
np.empty((5,5))

array([[1.89146896e-307, 1.37961302e-306, 6.23053614e-307,
        1.46361871e-311, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
                    nan, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [1.60220596e-306, 1.60219035e-306, 1.42410974e-306,
        2.56761491e-312, 5.97819431e-322]])

In [21]:
#数据类型转换
data=np.array([[1,2,3],[4,5,6]])
print(data.dtype)

float_data=data.astype(np.float64)
print(float_data.dtype)

int32
float64


In [42]:
float_data=np.array([[1.1,1.2,1.4],[2.5,3.6,4.9]])
print(float_data)

print()

int_data=float_data.astype(np.int64)
print(int_data)

[[1.1 1.2 1.4]
 [2.5 3.6 4.9]]

[[1 1 1]
 [2 3 4]]


In [43]:
#向量运算
data1=np.array([[1,2],[3,4]])
data2=np.array([[1,2],[3,4]])

data1+data2

array([[2, 4],
       [6, 8]])

In [46]:
#切片
arr=np.arange(8)
print(arr)
print(arr[5])
print(arr[3:5])
print(arr[1:6:2])

[0 1 2 3 4 5 6 7]
5
[3 4]
[1 3 5]


In [48]:
#数组转置
arr=np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [49]:
arr.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [51]:
arr=np.arange(16).reshape((2,2,4))
arr.transpose(1,2,0)

array([[[ 0,  8],
        [ 1,  9],
        [ 2, 10],
        [ 3, 11]],

       [[ 4, 12],
        [ 5, 13],
        [ 6, 14],
        [ 7, 15]]])

In [53]:
#数组排序
arr=np.array([[6,2,7],[3,6,2],[4,3,2]])

In [55]:
arr.sort()
arr

array([[2, 6, 7],
       [2, 3, 6],
       [2, 3, 4]])

In [57]:
arr=np.array([[6,2,7],[3,6,2],[4,3,2]])
arr.sort(0)
arr

array([[3, 2, 2],
       [4, 3, 2],
       [6, 6, 7]])

In [58]:
#检索
np.any(arr>0)

True

In [59]:
np.any(arr<0)

False

In [61]:
#随机数生成
np.random.seed(0)
np.random.rand(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

# Numpy 切片


In [30]:
#创建5x5二维数组
matrix=np.arange(0,60,10)
print(matrix)

#转换为列向量
matrix=matrix.reshape(-1,1)
print(matrix)

#利用广播机制，将列向量与行向量相加
matrix=matrix+np.arange(6)
print(matrix)

[ 0 10 20 30 40 50]
[[ 0]
 [10]
 [20]
 [30]
 [40]
 [50]]
[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [32]:
#红框切片提取第三列
red_data=matrix[:,2]
red_data


array([ 2, 12, 22, 32, 42, 52])

In [33]:
#橙框切片提取第一行的第三、第四列元素
orange_data=matrix[0,[3,4]]
orange_data


array([3, 4])

In [37]:
#绿框切片提取第一、三、五行的第三、五列元素
green_data=matrix[np.ix_([2,4],[0,2,4])]
green_data

array([[20, 22, 24],
       [40, 42, 44]])