# 张量练习部分

In [102]:
#其他
import matplotlib
import numpy as np

#torch库
import torch
print(torch.__version__)

2.6.0+cu126


In [103]:
%matplotlib inline

In [104]:
#直接数据创建Tensor
data=[[1,2],[3,4]]
x_data=torch.Tensor(data)
x_data

tensor([[1., 2.],
        [3., 4.]])

In [105]:
#numpy创建Tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [106]:
#其他Tensor创建
#保留x数据的属性
x_ones=torch.ones_like(x_data) 
print(f"Ones Tensor: \n {x_ones} \n")
#覆盖x_data的属性
x_rand = torch.rand_like(x_data, dtype=torch.float) 
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1., 1.],
        [1., 1.]]) 

Random Tensor: 
 tensor([[0.2053, 0.5238],
        [0.1570, 0.5318]]) 



In [107]:
#从常数、随机数创建
shape=(2,3,)

rand_tensor=torch.rand(shape)
ones_tensor=torch.ones(shape)
zeros_tensor=torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.3533, 0.6410, 0.7110],
        [0.0739, 0.5507, 0.5211]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [108]:
#Tensor属性
tensor=torch.rand(3,4)

print(f"形状: {tensor.shape}")
print(f"数据类型: {tensor.dtype}")
print(f"存储设备: {tensor.device}")

形状: torch.Size([3, 4])
数据类型: torch.float32
存储设备: cpu


In [109]:
#将Tensor移动到GPU
if torch.cuda.is_available():
    tensor=tensor.to('cuda')

print(f"存储位置：{tensor.device}")

存储位置：cuda:0


In [110]:
#Tensor索引与切片
tensor=torch.ones(4,4)
tensor[:,1]=0 #第2列为0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

In [111]:
#合并Tensors
t1=torch.cat([tensor,tensor,tensor],dim=1) #输入张量，沿着第二个维度（列）将多个张量拼接
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [112]:
#增加Tensor
#张量逐元素相乘
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



In [113]:
#张量和张量的转置的乘
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
#等价语句:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [114]:
#原地操作（不建议使用）
tensor=torch.ones(4,4)
tensor[:,1]=0
print(tensor,'\n')
tensor.add_(5)
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])

In [115]:
#numpy数组转化为Tensor
t=torch.ones(5)
print(f"t:{t}")

n=t.numpy()
print(f"n:{n}")

t:tensor([1., 1., 1., 1., 1.])
n:[1. 1. 1. 1. 1.]


In [116]:
#tensor的改变会反映在转换后的numpy数组中
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")
t.add_(1)
print(f"t:{t}")
print(f"n:{n}")

t:tensor([2., 2., 2., 2., 2.])
n:[2. 2. 2. 2. 2.]
t:tensor([3., 3., 3., 3., 3.])
n:[3. 3. 3. 3. 3.]


In [117]:
#numpy转Tensor
n=np.ones(5)
t=torch.from_numpy(n)
#同样会反映
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]


# 题目

## 1.张量创建与基础

In [118]:
#创建
t1=torch.ones(3,3)
print(t1)

#所有元素乘2
t1=t1*2
print(t1)

#减去
t1=t1-t1/4
print(t1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000]])


## 2. 索引与切片

In [119]:
#给定随机张量
t2=torch.rand(4,5)
print(t2,'\n')

#提取前两行
temp=t2[[0,1],:]
print(temp,'\n')

#提取后三列
temp=t2[:,[-3,-2,-1]]
print(temp,'\n')

#1行3列、2行4列设为-1
t2[0,2]=t2[1,3]=-1
print(t2,'\n')

tensor([[0.7476, 0.4022, 0.3695, 0.0197, 0.0022],
        [0.9305, 0.0982, 0.2617, 0.9344, 0.8546],
        [0.0993, 0.4415, 0.3150, 0.1663, 0.3999],
        [0.2127, 0.6724, 0.2030, 0.9079, 0.5414]]) 

tensor([[0.7476, 0.4022, 0.3695, 0.0197, 0.0022],
        [0.9305, 0.0982, 0.2617, 0.9344, 0.8546]]) 

tensor([[0.3695, 0.0197, 0.0022],
        [0.2617, 0.9344, 0.8546],
        [0.3150, 0.1663, 0.3999],
        [0.2030, 0.9079, 0.5414]]) 

tensor([[ 0.7476,  0.4022, -1.0000,  0.0197,  0.0022],
        [ 0.9305,  0.0982,  0.2617, -1.0000,  0.8546],
        [ 0.0993,  0.4415,  0.3150,  0.1663,  0.3999],
        [ 0.2127,  0.6724,  0.2030,  0.9079,  0.5414]]) 



## 3. 矩阵乘法

In [120]:
#创建A
a=torch.rand(2,3)
print(a,'\n')
#创建B
b=torch.rand(3,2)
print(b,'\n')

#矩阵相乘
m=a.matmul(b)
print(m,'\n')
print(m.shape,'\n')

tensor([[0.1531, 0.2218, 0.6731],
        [0.5744, 0.5246, 0.0841]]) 

tensor([[0.0810, 0.8807],
        [0.7769, 0.7713],
        [0.5091, 0.3320]]) 

tensor([[0.5274, 0.5294],
        [0.4969, 0.9383]]) 

torch.Size([2, 2]) 



## 4. 统计操作

In [121]:
#创建
t4=torch.rand(10,)
print(t4,'\n')

mean=t4.mean() #均值
std=t4.std() #标准差
max_val, max_idx = torch.max(t4, dim=0)  # 最大值及其索引
min_val, min_idx = torch.min(t4, dim=0)  # 最小值及其索引

print(f"均值: {mean:.4f}")
print(f"标准差: {std:.4f}")
print(f"最大值: {max_val:.4f}, 索引: {max_idx.item()}")
print(f"最小值: {min_val:.4f}, 索引: {min_idx.item()}")


tensor([0.2462, 0.4794, 0.1639, 0.5403, 0.6304, 0.6053, 0.6320, 0.4510, 0.2778,
        0.5303]) 

均值: 0.4557
标准差: 0.1693
最大值: 0.6320, 索引: 6
最小值: 0.1639, 索引: 2


# 5. 形状变换与广播

In [122]:
#创建
t5=torch.rand(5,4)
print(t5,'\n')

#转换形状
temp=t5.reshape(2,10)
print(temp,'\n')


tensor([[0.9595, 0.5759, 0.7973, 0.4766],
        [0.2544, 0.6600, 0.8836, 0.5635],
        [0.4927, 0.9695, 0.9710, 0.2926],
        [0.7057, 0.5647, 0.2815, 0.1466],
        [0.2417, 0.5393, 0.6310, 0.3542]]) 

tensor([[0.9595, 0.5759, 0.7973, 0.4766, 0.2544, 0.6600, 0.8836, 0.5635, 0.4927,
         0.9695],
        [0.9710, 0.2926, 0.7057, 0.5647, 0.2815, 0.1466, 0.2417, 0.5393, 0.6310,
         0.3542]]) 



In [123]:
#创建
a=torch.full((3,1),2)
print(a,'\n')

b=torch.full((1,4),3)
print(b,'\n')

#广播相加
c=a+b
print(c,'\n')

tensor([[2],
        [2],
        [2]]) 

tensor([[3, 3, 3, 3]]) 

tensor([[5, 5, 5, 5],
        [5, 5, 5, 5],
        [5, 5, 5, 5]]) 



## 6. 梯度计算

In [129]:
#创建
x1=[2.0,3.0]
t=torch.tensor(x1,requires_grad=True) #启用梯度跟踪
print(t,'\n')

#函数定义
y =3*t**2+2*t+1
print(y,'\n')

#梯度计算
y_sum=y.sum()
y_sum.backward()#计算梯度

# 打印结果
print("张量 t:", t)
print("函数 y:", y)
print("梯度 t.grad:", t.grad)

# 验证梯度是否正确
expected_grad = 6 * t.detach() + 2
print("计算得到梯度:", expected_grad)
print("梯度是否一致:", torch.allclose(t.grad, expected_grad))


tensor([2., 3.], requires_grad=True) 

tensor([17., 34.], grad_fn=<AddBackward0>) 

张量 t: tensor([2., 3.], requires_grad=True)
函数 y: tensor([17., 34.], grad_fn=<AddBackward0>)
梯度 t.grad: tensor([14., 20.])
计算得到梯度: tensor([14., 20.])
梯度是否一致: True
